/*
  Seed lecturers scraped from CTU staff pages 16-22.
  Safe to re-run: script skips existing lecturers by full_name.
*/

SET NOCOUNT ON;

DECLARE @fallbackFacultyCode NVARCHAR(50) = 'FIT';
DECLARE @existingImported INT = (
    SELECT COUNT(*)
    FROM lecturers
    WHERE lecturer_code LIKE 'CTUIMP%'
);

WITH src(full_name, specialization) AS (
    SELECT * FROM (VALUES
        (N'Phan Thanh Thuận', N'Công nghệ môi trường'),
        (N'Nguyễn Thị Như Ngọc', N'Nuôi trồng thủy sản'),
        (N'Nguyễn Như Phương', N'Sinh học phân tử'),
        (N'Nguyễn Hữu Tri', N'GD thể chất'),
        (N'Sơn Chanh Đa', N'Văn hóa học'),
        (N'Nguyễn Hoàng Thái', N'LL&PP dạy Tiếng Pháp'),
        (N'Phan Việt Thắng', N'LL&PP dạy tiếng Anh'),
        (N'Cao Mỹ Khanh', N'Du lịch'),
        (N'Trương Thị Kim Thủy', N'Văn hóa học'),
        (N'Trịnh Chí Thâm', N'Khoa học giáo dục'),
        (N'Trần Vũ Thị Giang Lam', N'Báo chí'),
        (N'Nguyễn Thụy Thùy Dương', N'Ngôn ngữ'),
        (N'Trần Đức Trung', N'Địa KT Xây Dựng'),
        (N'Hoàng Đăng Khoa', N'Thiết bị mạng, điện'),
        (N'Nguyễn Minh Nhựt', N'CN Hóa học'),
        (N'Trần Nguyễn Minh Thái', N'Kỹ thuật Máy tính'),
        (N'Nguyễn Thị Hồng Dân', N'Toán ứng dụng'),
        (N'Lê Thị Diệu Hiền', N'Quản trị Kinh doanh'),
        (N'Hoàng Thị Hồng Lộc', N'Chính sách công'),
        (N'Trần Thị Hạnh Phúc', N'Tài chính-Ngân hàng'),
        (N'Nguyễn Tấn Tài', N'Kế toán'),
        (N'Nguyễn Xuân Vinh', N'Quản trị Kinh doanh'),
        (N'Nguyễn Thị Mỹ Linh', N'Luật dân sự và tố tụng dân sự'),
        (N'Đoàn Nguyễn Minh Thuận', N'Luật Kinh tế'),
        (N'Trần Hồng Trang', N'Lịch sử Đảng CSVN'),
        (N'Nguyễn Thị Bạch Tuyết', N'Kinh tế chính trị'),
        (N'Hồ Thị Hà', N'Triết học'),
        (N'Nguyễn Thị Kim Quế', N'Lịch sử Đảng CSVN'),
        (N'Phạm Việt Nữ', N'KH Môi trường'),
        (N'Nguyễn Thị Bích Nhi', N'LL&PP dạy tiếng Anh'),
        (N'Lâm Thị Việt Hà', N'Công nghệ Sinh học'),
        (N'Lê Văn Hiệu', N'Địa lý'),
        (N'Phạm Thị Phượng Linh', N'Lịch sử thế giới'),
        (N'Hà Hoàng Quốc Thi', N'Khai thác dữ liệu'),
        (N'Trang Văn Dể', N'Đại số & Lý thuyết số'),
        (N'Nguyễn Trần Huỳnh Mai', N'Quản lý giáo dục'),
        (N'Phạm Phú Cường', N'kỹ thuật Điện tử'),
        (N'Trần Phước Lộc', N'LTXS & Tkê Toán học'),
        (N'Lê Hoài Nhân', N'Toán giải tích'),
        (N'Nguyễn Ánh Minh', N'Chính sách công'),
        (N'Huỳnh Thị Trúc Giang', N'Luật Kinh tế'),
        (N'Nguyễn Thái Sơn', N'KT điện'),
        (N'Bùi Văn Hữu', N'Phát triển giao thông & đô thị'),
        (N'Cao Ngọc Báu', N'Giáo dục học'),
        (N'Đặng Vũ Kim Chi', N'Giáo dục học'),
        (N'Thạch Chanh Đa', N'Văn hóa Khmer Nam Bộ'),
        (N'Tăng Thị Lệ Huyền', N'LL&PP dạy tiếng Anh'),
        (N'Ngô Mi Lệ Anh', N'Ngôn ngữ học ứng dụng'),
        (N'Nguyễn Đình Lý', N'Xây dựng Đảng'),
        (N'Trần Lê Trung Chánh', N'KT Điều khiển & tự động hóa'),

        (N'Nguyễn Thị Trâm', N'kỹ thuật Điện tử'),
        (N'Lê Thị Thúy Hương', N'Hồ Chí Minh học'),
        (N'Trần Thị Như Tuyến', N'Triết học'),
        (N'Nguyễn Khánh Linh', N'Triết học'),
        (N'Hồ Hồng Liên', N'Tài chính kế toán'),
        (N'Lê Tín', N'Kinh tế'),
        (N'Đinh Công Thành', N'Quản trị Kinh doanh'),
        (N'Đặng Thị Phượng', N'KT Nông nghiệp'),
        (N'Nguyễn Thanh Trí', N'Công nghệ thực phẩm'),
        (N'Lưu Bích Ngọc', N'Giao tiếp đa văn hoá'),
        (N'Nguyễn Thị Hà', N'Vi sinh vật'),
        (N'Hoàng Hải Yến', N'Hóa phân tích'),
        (N'Trần Thụy Quốc Thái', N'Luật Kinh tế'),
        (N'Bùi Thị Mỹ Hương', N'Luật hợp tác kinh tế'),
        (N'Nguyễn Thị Ngọc Tuyền', N'Luật Kinh tế'),
        (N'Nguyễn Chí Hiếu', N'Luật Kinh tế'),
        (N'Đặng Thị Tuyết Mai', N'Hoá LT và hoá lý'),
        (N'Phạm Bích Như', N'Toán giải tích'),
        (N'Lê Thị Ngọc Xuân', N'Trồng trọt'),
        (N'Nguyễn Thị Kim Thi', N'LL&PP dạy tiếng Anh'),
        (N'Trương Thị Mộng Thu', N'Công nghệ Sinh học'),
        (N'Trần Thị Mỹ Dung', N'Quản lý công nghiệp'),
        (N'Nguyễn Thị Lệ Thủy', N'Quản lý công nghiệp'),
        (N'Lê Đức Duy', N'Hóa học'),
        (N'Nguyễn Hồng Đức', N'Phát triển bền vững'),
        (N'Lê Phương Hùng', N'GD thể chất'),
        (N'Mai Lê Trúc Liên', N'Tài chính-Ngân hàng'),
        (N'Phạm Mai Phương', N'Luật Kinh tế'),
        (N'Nguyễn Phan Khôi', N'Luật thương mại'),
        (N'Nguyễn Ngọc Phương Thảo', N'Khoa học giáo dục'),
        (N'Trần Thị Hải Yến', N'Lịch sử thế giới'),
        (N'Trần Nguyên Hương Thảo', N'LL&PPdạy Văn& TViệt'),
        (N'Đặng Thị Kim Oanh', N'Triết học'),
        (N'Nguyễn Xuân Hương', N'Chính trị học'),
        (N'Nguyễn Thị Đan Thụy', N'Triết học'),
        (N'Huỳnh Thị Kim Uyên', N'Kinh tế'),
        (N'Huỳnh Thị Đan Xuân', N'KT Nông nghiệp'),
        (N'Trần Quế Anh', N'Kinh doanh & Quản lý'),
        (N'Nguyễn Thúy An', N'Kế toán'),
        (N'Trương Thị Thúy Hằng', N'Kế toán-Kiểm toán'),
        (N'Huỳnh Nhựt Phương', N'Marketing'),
        (N'Huỳnh Thị Tuyết Sương', N'Tài chính-Ngân hàng'),
        (N'Nguyễn Đỗ Châu Giang', N'Nông nghiệp'),
        (N'Lăng Cảnh Phú', N'KH Nông nghiệp'),
        (N'Nguyễn Anh Duy', N'XD Dân dụng& CNghiệp'),
        (N'Hồ Văn Thắng', N'Địa KT Xây Dựng'),
        (N'Trần Thị Phượng', N'Địa KT Xây Dựng'),
        (N'Nguyễn Quốc Nghi', N'Điều khiển tự động'),
        (N'Nguyễn Việt Bách', N'Kỹ thuật hóa học'),
        (N'Nguyễn Văn Sơn', N'Kết cấu công trình'),

        (N'Lê Tuấn Tú', N'XD Dân dụng& CNghiệp'),
        (N'Trần Anh Nguyện', N'KT điện'),
        (N'Phan Trọng Nghĩa', N'Thiết bị, mạng và nhà máy điện'),
        (N'Đào Minh Trung', N'NC Đông Nam á'),
        (N'Nguyễn Hào Nhán', N'Thiết bị, mạng và nhà máy điện'),
        (N'Phùng Thị Hằng', N'Sinh lý thực vật'),
        (N'Đinh Thanh Phương', N'Luật học'),
        (N'Nguyễn Thị Liên', N'Công nghệ Sinh học'),
        (N'Đồng Thanh Hải', N'LL&PP dạy tiếng Anh'),
        (N'Đoàn Thu Ánh Điểm', N'GD thể chất'),
        (N'Tạ Đức Tú', N'Hán nôm'),
        (N'Nguyễn Thu Nha Trang', N'Kế toán'),
        (N'Phan Thị Ánh Nguyệt', N'Kế toán'),
        (N'Lương Thị Cẩm Tú', N'Kế toán'),
        (N'Nguyễn Thị Ngọc Hoa', N'Quản trị Kinh doanh'),
        (N'Lê Thị Thu Trang', N'Quản trị Kinh doanh'),
        (N'Trương Thị Bích Liên', N'Tài chính'),
        (N'Bùi Lê Thái Hạnh', N'Kinh tế & QL thủy sản'),
        (N'Vũ Thùy Dương', N'KT Nông nghiệp'),
        (N'Dương Quế Nhu', N'Kinh tế'),
        (N'Trương Khánh Vĩnh Xuyên', N'Kinh doanh & Quản lý'),
        (N'Nguyễn Mộng Hoàng', N'Hóa lý thuyết&Hóa lý'),
        (N'Đặng Thị Hoa', N'Văn hóa&Ngôn ngữ TQ'),
        (N'Hồng Lư Chí Toàn', N'LL&PP dạy tiếng Anh'),
        (N'Lê Thị Mỹ Xuân', N'Lý thuyết tối ưu'),
        (N'Huỳnh Thị Trúc Phương', N'Thông tin thư viện'),
        (N'Lê Ngọc Linh', N'Thông tin thư viện'),
        (N'Nguyễn Thị Bích Ngọc', N'Thông tin thư viện'),
        (N'Lâm Thị Hương Duyên', N'Thông tin thư viện'),
        (N'Lý Thành Lũy', N'CN Thông tin'),
        (N'Phạm Anh Du', N'Địa KT Xây Dựng'),
        (N'Nguyễn Tấn Đạt', N'Kỹ thuật cơ khí'),
        (N'Châu Minh Khải', N'Quản lý đô thị và công trình'),
        (N'Sử Kim Anh', N'Hệ thống thông tin'),
        (N'Võ Phạm Trinh Thư', N'Ngôn ngữ học ứng dụng'),
        (N'Lý Hồng Thái', N'Ngôn ngữ học ứng dụng'),
        (N'Trần Minh Tân', N'Hệ thống thông tin'),
        (N'Huỳnh Trung Vũ', N'Giáo dục khoa học'),
        (N'Nguyễn Phạm Tuyết Anh', N'Quản trị Kinh doanh'),
        (N'Nguyễn Huy Tài', N'QLTNTN&NNBvững'),
        (N'Võ Mạnh Duy', N'Công nghệ nhiệt'),
        (N'Trần Trang Nhất', N'KTXD công trình giao thông'),
        (N'Trần Chinh Phong', N'Kiến trúc'),
        (N'Đinh Thị Chinh', N'Lịch sử Đảng CSVN'),
        (N'Lê Ngọc Lan', N'Thông tin thư viện'),
        (N'Nguyễn Thị Hồng Vân', N'KH Thủy sản'),
        (N'Nguyễn Thị Kim Hà', N'KT Nông nghiệp'),
        (N'Nguyễn Thị Ánh Hồng', N'Hóa lý thuyết&Hóa lý'),
        (N'Trần Thị Ngọc Thảo', N'Vật lý kỹ thuật'),
        (N'Nguyễn Thị Thúy Hằng', N'VL Lý thuyết&VL Toán'),

        (N'Bùi Anh Tuấn', N'LL&PP dạy toán'),
        (N'Mạc Giáng Châu', N'Luật Kinh tế'),
        (N'Nguyễn Hữu Lạc', N'Luật Kinh tế'),
        (N'Trương Thanh Hùng', N'Luật hình sự'),
        (N'Võ Hoàng Yến', N'Luật Kinh tế'),
        (N'Tăng Thanh Phương', N'Luật Dân Sự'),
        (N'Lâm Chí Nguyện', N'Khai phá dữ liệu'),
        (N'Phạm Xuân Hiền', N'Hệ thống thông tin'),
        (N'Huỳnh Thị Sinh Hiền', N'Luật thương mại'),
        (N'Lê Huỳnh Phương Chinh', N'Luật Quốc tế&So sánh'),
        (N'Nguyễn Mai Hân', N'Luật Quốc tế&So sánh'),
        (N'Vũ Xuân Nam', N'Tài chính-Ngân hàng'),
        (N'Võ Văn Đấu', N'KT Xây dựng'),
        (N'Huỳnh Long Toản', N'KH Môi trường'),
        (N'Nguyễn Trường Thành', N'QL&CN Môi trường'),
        (N'Lê Vĩnh Trường', N'Thiết bị, mạng và nhà máy điện'),
        (N'Đinh Mạnh Tiến', N'Vật lý kỹ thuật'),
        (N'Lê Nông', N'XD Dân dụng& CNghiệp'),
        (N'Phạm Mai Anh', N'LL&PP dạy tiếng Anh'),
        (N'Phạm Văn Bình', N'KT Điều khiển & tự động hóa'),
        (N'Trần Hoàng Tuấn', N'Xây Dựng'),
        (N'Châu Đức Thành', N'GD thể chất'),
        (N'Tống Lê Minh', N'GD thể chất'),
        (N'Đoàn Anh Dũng', N'Công nghệ thực phẩm'),
        (N'Khưu Quốc Duy', N'Quản lý giáo dục'),
        (N'Phạm Thị Mai Duyên', N'CNGiaotiếp&TTtrongGD'),
        (N'Thái Thị Tuyết Nhung', N'Hóa hữu cơ'),
        (N'Huỳnh Hoang Khả', N'Địa lý'),
        (N'Lê Thành Nghề', N'Địa lý tự nhiên'),
        (N'Hồ Văn Tú', N'Hệ thống thông tin'),
        (N'Huỳnh Phụng Toàn', N'Hệ thống thông tin'),
        (N'Đặng Long Quân', N'VL Kỹ thuật'),
        (N'Trần Yến Mi', N'VL Lý thuyết&VL Toán'),
        (N'Phan Huy Cường', N'Hệ thống thông tin'),
        (N'Nguyễn Khắc Nguyên', N'Tự động hóa'),
        (N'Nguyễn Đăng Khoa', N'Thiết bị, mạng và nhà máy điện'),
        (N'Trần Thị Tuyết Hà', N'Tôn giáo'),
        (N'Võ Hồng Phượng', N'Quản trị Kinh doanh'),
        (N'Nguyễn Thúy Hằng', N'KT Tài nguyên MT'),
        (N'Trần Thụy Ái Đông', N'KTế TN môi trừơng'),
        (N'Đoàn Thị Cẩm Vân', N'KT Tàichính-Ngânhàng'),
        (N'Nguyễn Thị Hồng Liễu', N'KT Nông nghiệp'),
        (N'Phạm Duy Nghiệp', N'KT Điều khiển & tự động hóa'),
        (N'Tăng Đinh Ngọc Thảo', N'Quản lý giáo dục'),
        (N'Nguyễn Hoàng Vĩnh Vương', N'Thông tin thư viện'),
        (N'Lê Văn Dũ', N'KH Môi trường'),
        (N'Huỳnh Thu Hạnh', N'Hóa lý thuyết&Hóa lý'),
        (N'Bùi Văn Tra', N'KT Điều khiển & tự động hóa'),
        (N'Nguyễn Thị Lương', N'KT Nông nghiệp'),
        (N'Lý Thị Bích Phượng', N'Ngôn ngữ học ứng dụng'),

        (N'Trần Mai Hiển', N'Giáo dục học'),
        (N'Dương Bích Thảo', N'Vật lý kỹ thuật'),
        (N'Lê Hoàng Thảo', N'CN Thông tin'),
        (N'Nguyễn Thanh Nhã', N'KT Điều khiển & tự động hóa'),
        (N'Trần Hữu Danh', N'kỹ thuật Điện tử'),
        (N'Thạch Huôn', N'Luật Quốc tế'),
        (N'Võ Kim Hương', N'Quản lý giáo dục'),
        (N'Phan Hồng Toàn', N'KT Điều khiển & tự động hóa'),
        (N'Dương Nguyễn Hồng Toàn', N'XD Dân dụng& CNghiệp'),
        (N'Nguyễn Văn Bạc', N'Quản lý thông tin'),
        (N'Cao Văn Quang', N'Quản lý giáo dục'),
        (N'Nguyễn Văn Ngân', N'Kinh tế phát triển'),
        (N'Nguyễn Văn Sáu', N'Giáo dục học'),
        (N'Trần Thị Anh Thư', N'Động vật học'),
        (N'Phạm Thị Bích Thủy', N'Sinh lý thực vật'),
        (N'Nguyễn Hoàng Xinh', N'Toán đại số'),
        (N'Bùi Thị Thúy Minh', N'VHTQ hiện &đương đại'),
        (N'Trần Văn Thịnh', N'Lý luận văn học'),
        (N'Trần Thanh Điện', N'Quản lý thông tin'),
        (N'Lê Thị Diễm', N'Hệ thống thông tin'),
        (N'Trần Vũ Phương', N'Công nghệ Sinh học'),
        (N'Nguyễn Hoàng Khoa', N'GD thể chất'),
        (N'Hồ Minh Nhị', N'Điện-Điện tử'),
        (N'Lê Thành Phiêu', N'QL Dự án XD'),
        (N'Lê Anh Kha', N'KH Môi trường'),
        (N'Nguyễn Thị Kim Phượng', N'Tài chính-Ngân hàng'),
        (N'Huỳnh Chí Minh Huyên', N'LL&PP dạy tiếng Anh'),
        (N'Nguyễn Thanh Tùng', N'LL&PP dạy tiếng Anh'),
        (N'Huỳnh Minh Hiền', N'LL&PP dạy tiếng Anh'),
        (N'Nguyễn Thái Hữu', N'LL&PP dạy tiếng Anh'),
        (N'Nguyễn Hoàng Long', N'Toán giải tích'),
        (N'Nguyễn Nhựt Duy', N'KT Điều khiển & tự động hóa'),
        (N'Dương Thái Bình', N'KT Điều khiển & tự động hóa'),
        (N'Diệp Thành Nguyên', N'Luật So sánh'),
        (N'Kim Oanh Na', N'Luật học'),
        (N'Nguyễn Thị Thảo Trúc', N'Toán giải tích'),
        (N'Nguyễn Thị Thùy Linh', N'Khoa học máy tính'),
        (N'Hoàng Minh Trí', N'Hệ thống thông tin'),
        (N'Nguyễn Công Huy', N'Hệ thống thông tin'),
        (N'Lưu Trùng Dương', N'Tin học'),
        (N'Trần Thy Linh Giang', N'Quản lý kinh tế'),
        (N'Lê Quang Viết', N'Quản trị Kinh doanh'),
        (N'Trần Bá Trí', N'Quản trị Kinh doanh'),
        (N'Huỳnh Văn Hiến', N'LL&PP dạy tiếng Anh'),
        (N'Trương Nguyễn Quỳnh Như', N'LL&PP dạy tiếng Anh'),
        (N'Lê Hữu Lý', N'LL&PP dạy tiếng Anh'),
        (N'Nguyễn Minh Thành', N'LL&PP dạy tiếng Anh'),
        (N'Phạm Hữu Tài', N'Hệ thống thông tin'),
        (N'Nguyễn Đức Khoa', N'Tin học'),
        (N'Đặng Hoàng Tâm', N'Toán giải tích'),

        (N'Hồ Thị Xuân Quỳnh', N'Lý luận văn học'),
        (N'Phan Tấn Tài', N'Phát triển HTTT'),
        (N'Võ Huỳnh Trâm', N'Khoa học máy tính'),
        (N'Trương Thị Thanh Tuyền', N'Hệ thống thông tin'),
        (N'Nguyễn Hứa Duy Khang', N'Điện tử-Viễn thông'),
        (N'Nguyễn Minh Luân', N'Điều khiển tự động'),
        (N'Đặng Thị Tầm', N'Dân tộc học'),
        (N'Đào Phong Lâm', N'Đánh giá&kiểm tra'),
        (N'Đàm Thị Phong Ba', N'KT Nông nghiệp'),
        (N'Nguyễn Minh Trung', N'Phát triển HTTT'),
        (N'Vũ Duy Linh', N'Hệ thống thông tin'),
        (N'Đặng Trâm Anh', N'Kỹ thuật giao thông'),
        (N'Mai Văn Trầm', N'Trồng trọt'),
        (N'Võ Duy Nam', N'QLHC Công'),
        (N'Nguyễn Thị Nguyên Tuyết', N'Quản lý giáo dục'),
        (N'Nguyễn Huỳnh Mai', N'Thông tin thư viện'),
        (N'Lê Hoàng Việt', N'KT&QL Môi trường'),
        (N'Ngô Thị Trang Thảo', N'LL&PP dạy tiếng Anh'),
        (N'Đỗ Văn Hoàng', N'Phát triển nông thôn'),
        (N'Nguyễn Hoàng Khải', N'Phát triển nông thôn'),
        (N'Nguyễn Văn Thái', N'GD thể chất'),
        (N'Lê Thị Bích Diễm', N'Hồ Chí Minh học'),
        (N'Phan Văn Thạng', N'CN Duy vật BC&CNDVLS'),
        (N'Nguyễn Ngọc Lam', N'KT Nông nghiệp'),
        (N'Thái Văn Đại', N'Quản trị Kinh doanh'),
        (N'Trần Quốc Dũng', N'Kinh tế'),
        (N'Nguyễn Thị Diệu', N'Quản trị Kinh doanh'),
        (N'Nguyễn Văn Duyệt', N'Quản trị Kinh doanh'),
        (N'Nguyễn Phạm Thanh Nam', N'Quản trị Kinh doanh'),
        (N'Huỳnh Kim Hoa', N'KT Điều khiển & tự động hóa'),
        (N'Hồ Ngọc Tri Tân', N'XD Dân dụng& CNghiệp'),
        (N'Hoàng Vĩ Minh', N'C.trình trên đất yếu'),
        (N'Trần Văn Hừng', N'Thủy nông'),
        (N'Trương Văn Thảo', N'Cơ khí'),
        (N'Nguyễn Quan Thanh', N'Cơ khí Giao Thông'),
        (N'Nguyễn Văn Long', N'Cơ khí nông nghiệp'),
        (N'Nguyễn Minh Trí', N'KTVLpolyme&Composite'),
        (N'Phan Thanh Lương', N'Cơ khí nông nghiệp'),
        (N'Nguyễn Văn Trí', N'CK chế tạo CN cao'),
        (N'Phạm Ngọc Long', N'Cơ khí nông nghiệp'),
        (N'Đoàn Phú Cường', N'Cơ khí'),
        (N'Phạm Hoàng Dũng', N'Nông nghiệp'),
        (N'Dương Trí Dũng', N'QLTH Tài nguyên biển'),
        (N'Nguyễn Thị Thu Thủy', N'Sinh hóa thực phẩm'),
        (N'Văn Minh Nhựt', N'Cơ khí nông nghiệp'),
        (N'Lê Công Tuấn', N'Ngôn ngữ học ứng dụng'),
        (N'Chung Thị Thanh Hằng', N'Giáo dục học'),
        (N'Hồ Phương Thùy', N'LL&PP dạy tiếng Anh'),
        (N'Huỳnh Trọng Nghĩa', N'Ngôn ngữ học ứng dụng'),

        (N'Lê Thanh Hùng', N'LL&PP dạy tiếng Anh'),
        (N'Nguyễn Thành Đức', N'LL&PP dạy tiếng Anh'),
        (N'Trương Thị Ngọc Điệp', N'Quản lý giáo dục'),
        (N'Bùi Minh Châu', N'Ngôn ngữ học ứng dụng'),
        (N'Nguyễn Thị Việt Anh', N'LL&PP dạy tiếng Anh'),
        (N'Nguyễn Hồng Quí', N'LL&PP dạy tiếng Anh'),
        (N'Châu Hoàng Trung', N'Địa lý tự nhiên'),
        (N'Hồ Thị Thu Hồ', N'Giáo dục khoa học'),
        (N'Lê Thị Minh Thu', N'Lịch sử Viêt Nam'),
        (N'Nguyễn Hữu Thành', N'LSửTG cận hiện'),
        (N'Võ Thị Thanh Phương', N'Khoa học giáo dục'),
        (N'Đặng Thị Bắc Lý', N'Nghiên cứu về KHCN'),
        (N'Nguyễn Thị Dơn', N'Sinh thái học'),
        (N'Phan Kim Định', N'Sinh thái học'),
        (N'Nguyễn Văn Đạt', N'Hóa học'),
        (N'Lê Thị Kiều Oanh', N'Toán giải tích'),
        (N'Dương Thị Tuyền', N'LTXS & Tkê Toán học'),
        (N'Nguyễn Đăng Qua', N'Xây dựng Đảng'),
        (N'Nguyễn Văn Luyện', N'Quân sự'),
        (N'Nguyễn Nhật Trường', N'Giáo dục Quốc phòng-An ninh'),
        (N'Huỳnh Văn Hải', N'Quân sự'),
        (N'Nguyễn Hoàng Thắng', N'KT C.trình'),
        (N'Ngô Nhã Lam Duy', N'SP Sinh'),
        (N'Phùng Văn Bền', N'Quân sự'),
        (N'Trần Văn Lý', N'Xây dựng Đảng'),
        (N'Lê Trường Giang', N'Quân sự'),
        (N'Vũ Văn Thắng', N'Xây dựng Đảng'),
        (N'Nguyễn Văn Thắng', N'Quân sự'),
        (N'Nguyễn Đức Cường', N'Quân sự'),
        (N'Mai Thế Tuấn', N'Quân sự'),
        (N'Võ Phước Hòa', N'Quân sự'),
        (N'Nguyễn Cộng Hòa', N'Quân sự'),
        (N'Vũ Đình Phương', N'Quân sự'),
        (N'Nguyễn Vĩnh Ninh', N'Chính trị học')
    ) AS v(full_name, specialization)
),
unique_src AS (
    SELECT full_name, MIN(specialization) AS specialization
    FROM src
    GROUP BY full_name
),
mapped AS (
    SELECT
        u.full_name,
        u.specialization,
        CASE
            WHEN u.specialization LIKE N'%thủy sản%' OR u.specialization LIKE N'%thủy nông%' THEN N'AQU'
            WHEN u.specialization LIKE N'%nông%' OR u.specialization LIKE N'%trồng trọt%' THEN N'AGR'
            WHEN u.specialization LIKE N'%thực phẩm%' THEN N'FST'
            WHEN u.specialization LIKE N'%kinh tế%' OR u.specialization LIKE N'%tài chính%' OR u.specialization LIKE N'%kế toán%' OR u.specialization LIKE N'%quản trị%' OR u.specialization LIKE N'%marketing%' THEN N'ECO'
            WHEN u.specialization LIKE N'%hệ thống thông tin%' OR u.specialization LIKE N'%khoa học máy tính%' OR u.specialization LIKE N'%tin học%' OR u.specialization LIKE N'%công nghệ thông tin%' THEN N'FIT'
            WHEN u.specialization LIKE N'%giáo dục%' OR u.specialization LIKE N'%ll&pp%' OR u.specialization LIKE N'%triết%' OR u.specialization LIKE N'%lịch sử%' OR u.specialization LIKE N'%ngôn ngữ%' OR u.specialization LIKE N'%luật%' OR u.specialization LIKE N'%văn%' THEN N'EDU'
            ELSE @fallbackFacultyCode
        END AS faculty_code
    FROM unique_src u
),
to_insert AS (
    SELECT
        m.full_name,
        m.specialization,
        f.id AS faculty_id,
        ROW_NUMBER() OVER (ORDER BY m.full_name) AS rn
    FROM mapped m
    INNER JOIN faculties f ON f.code = m.faculty_code
    WHERE NOT EXISTS (
        SELECT 1
        FROM lecturers l
        WHERE UPPER(l.full_name) = UPPER(m.full_name)
    )
)
INSERT INTO lecturers (id, lecturer_code, full_name, faculty_id, subject_id, status)
SELECT
    NEWID(),
    N'CTUIMP' + RIGHT('00000' + CAST(@existingImported + rn AS VARCHAR(5)), 5),
    full_name,
    faculty_id,
    NULL,
    N'ACTIVE'
FROM to_insert;

SELECT @@ROWCOUNT AS inserted_rows;
